[package]
name = "latex"
version = "0.2.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.40"
serde = "1.0.210"
serde_with = "3.11.0"
zed_extension_api = "0.7.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true
